Repository cloud-native-toolkit/terraform-vsi-vpn, pull requests merged in 2021-05, with the labels that each got.

#12 Security Rule Update
  main.tf
Labels: feature, minor

#13 Harden Security Group rules
  main.tf
Labels: feature, minor

#14 Rebuilds module to use ibm-vpc-vsi module
  main.tf
  outputs.tf
  test/stages/stage1-bastion.tf
  variables.tf
Labels: feature, minor

#15 Updates bastion submodule
  main.tf
  module.yaml
Labels: chore, patch

#16 Updates module metadata
  main.tf
  variables.tf
Labels: chore, patch

#17 Adds allow_deprecated_image flag from vpc-vsi and set false in test
  main.tf
  test/stages/stage2-openvpn.tf
  variables.tf
Labels: chore, patch

#18 Adds names to the output variables
  main.tf
  outputs.tf
  test/stages/stage1-bastion-subnets.tf
  test/stages/stage1-gateways.tf
  test/stages/stage2-openvpn-subnets.tf
  test/stages/stage2-openvpn.tf
Labels: feature, patch

#19 Moves flow-log logic and variables to separate module
  main.tf
  module.yaml
  variables.tf
Labels: feature, minor

#20 Updates ibm-vsi-bastion to v1.4.1
  main.tf
Labels: enhancement, patch

#21 Updates security group
  main.tf
  scripts/openvpn-config.sh
  test/stages/stage1-bastion-subnets.tf
  test/stages/stage1-gateways.tf
  test/stages/stage2-openvpn-subnets.tf
  variables.tf
Labels: enhancement, minor

#23 Adds base_security_group variable definition to metadata
  module.yaml
Labels: chore, patch

#24 Bumps vsi-bastion to v1.6.0 to get updated maintenance sg
  main.tf
  outputs.tf
Labels: enhancement, minor

#28 Updates networking for OpenShift private endpoints
  main.tf
  scripts/openvpn-config.sh
Labels: bug, patch

#29 OpenVPN tuned for Ubuntu (#27)
  main.tf
  scripts/openvpn-config.sh
  test/stages/stage1-vpc-ssh.tf
  variables.tf
Labels: feature, minor
